### ISSUE TITLE
Bad link in wiki for TravelerBehaviorData

### ISSUE THREAD

**Issue by 3vivekb** [BayAreaMetro/modeling-website#2]
This link in the wiki under TravelerBehaviorData is bad
Household Travel Surveys
-Information on 1946/47, 1965, 1981, 1990, 1996, and 2000 Surveys

**Comment by lmz** [comment]
I think this site doesn't exist any longer.  It used to look like this: https://web.archive.org/web/20100304122031/http://www.mtc.ca.gov/maps_and_data/datamart/survey/

@shimonisrael, do you know?

**Comment by shimonisrael** [comment]
I recognize the site from early days at MTC, but am uncertain what happened to it. Kearey might know that. The files, however, are available elsewhere. Archived here:  \\\mtcarchives\cloudmodels1\Archived M Drive\Chuck Purvis M

FTP here: ftp://ftp.abag.ca.gov/pub/mtc/planning/

**Comment by lmz** [comment]
Updated link to point to ftp
