### ISSUE TITLE
A format issue on the SetupConfiguration wiki page

### ISSUE THREAD

**Issue by alexmitrani** [BayAreaMetro/modeling-website#4]
On the SetupConfiguration page (https://github.com/BayAreaMetro/modeling-website/wiki/SetupConfiguration) the formatting is a bit confusing because the text starting "The INPUT directory" is part of the same paragraph as the "scripts" bullet point.  

![image](https://user-images.githubusercontent.com/27974470/117906872-bc177780-b2a3-11eb-94c8-3064f1afa9f9.png)

The text starting "The INPUT directory" should probably be a separate paragraph with hwy, trn, etc. as bullet points beneath it.  

Thanks

**Comment by lmz** [comment]
Thanks for this note!  I updated, and updated the remainder of this page as well since there was some other info that was out of date; RunModel.bat now automatically starts and stops the required java and Voyager processes so those sections were out of date.

**Comment by alexmitrani** [comment]
Great, thanks very much @lmz
